package net.martenscs.cxf.contract.doubleit;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-10-28T10:55:08.697-05:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "DoubleItService", 
                  wsdlLocation = "classpath:DoubleIt.wsdl",
                  targetNamespace = "http://cxf.martenscs.net/contract/DoubleIt") 
public class DoubleItService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.martenscs.net/contract/DoubleIt", "DoubleItService");
    public final static QName DoubleItPort = new QName("http://cxf.martenscs.net/contract/DoubleIt", "DoubleItPort");
    static {
        URL url = DoubleItService.class.getClassLoader().getResource("DoubleIt.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DoubleItService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:DoubleIt.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public DoubleItService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoubleItService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoubleItService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoubleItService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoubleItService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoubleItService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DoubleItPortType
     */
    @WebEndpoint(name = "DoubleItPort")
    public DoubleItPortType getDoubleItPort() {
        return super.getPort(DoubleItPort, DoubleItPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoubleItPortType
     */
    @WebEndpoint(name = "DoubleItPort")
    public DoubleItPortType getDoubleItPort(WebServiceFeature... features) {
        return super.getPort(DoubleItPort, DoubleItPortType.class, features);
    }

}
