package net.martenscs.cxf.contract.doubleit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-10-28T10:55:08.614-05:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://cxf.martenscs.net/contract/DoubleIt", name = "DoubleItPortType")
@XmlSeeAlso({net.martenscs.cxf.schema.doubleit.ObjectFactory.class})
public interface DoubleItPortType {

    @WebResult(name = "doubledNumber", targetNamespace = "")
    @RequestWrapper(localName = "DoubleIt", targetNamespace = "http://cxf.martenscs.net/schema/DoubleIt", className = "net.martenscs.cxf.schema.doubleit.DoubleIt")
    @WebMethod(operationName = "DoubleIt")
    @ResponseWrapper(localName = "DoubleItResponse", targetNamespace = "http://cxf.martenscs.net/schema/DoubleIt", className = "net.martenscs.cxf.schema.doubleit.DoubleItResponse")
    public int doubleIt(
        @WebParam(name = "numberToDouble", targetNamespace = "")
        int numberToDouble
    );
}
